### ISSUE TITLE
Update the test case section 

### ISSUE THREAD

**Issue by jaghili** [master-csmi/2024-m1-algstruct#41]
Add the following figures : 
1. A figure where we plot $x_1,\ldots x_m$ close to the dataset $\cal{D}$ (but differents !) and also $x_i \oplus_\theta x_j$ for each pair $(i,j)$ and also the quantity $f_\theta (f_\theta^{-1}(x_i) + f_\theta^{-1}(x_j))$ for each pair 
2. the same for $\odot_\theta$ 
3. and  plot of the images $f_\theta(x_i)$ for each $x_i$ 
4. plot several lines $\cal{D}_1,\ldots,\cal{D}_4$ around $(Ox)$ and plot the image by $f_\theta$.

**Comment by chahid-rahouti** [comment]
![test](https://github.com/master-csmi/2024-m1-algstruct/assets/154335126/d866f8aa-0429-4c6d-af74-8572b7f48892)
hi sir, please can you verify these plot to see if the result we have is correct.
the prediction changes everytime, but it is the same. Is it possible to have a meeting tomorrow to discuss about it
@jaghili, @Blessed-joseph

**Comment by chahid-rahouti** [comment]
Y - Xi is our loss

**Comment by jaghili** [comment]
Replot as a table in the following way : 

For any couple of points $(y_i, t_i)$ compute the associated error $||x_i \oplus_\theta x_j - f_\theta (f_\theta^{-1}(x_i) + f_\theta^{-1}(x_j))||$  list them as a table 

|y_i|t_i|err_i|
